### PR TITLE
Initial pass at filters

### PR DESCRIPTION
**Pull request by seandavi**
This certainly isn't clean, but this is my first foray into using R symbol tree parsing.  Very cool stuff.  Needs a lot of checking, etc., but as it stands, an end-user can use "quoted" R syntax to generate json that corresponds to available filters on a generic GDC endpoint.  

I suspect this will need some further work, so feel free to ignore this alpha-level code if you like and wait for me to clean it up.

### CODE REVIEW

**Comment by lawremi** [comment]
This looks like a good start. I usually approach this problem by defining promise types. That allows much more flexibility, such as writing a custom filter function that is defined in terms of the primitive operators.

**Comment by seandavi** [comment]
Can I bother you to point me to an example?

**Comment by lawremi** [comment]
I guess you could look at https://github.com/lawremi/rsolr/blob/master/R/SolrPromise-class.R. But it's a bit complex. This case is *much* simpler. The basic idea is to evaluate the expression in an environment where there is a promise object for all symbols in the expression (i.e., `all.vars(expr)`). Then define a method on "Logic" for that promise class that returns a promise representing the call. You probably only need a single promise class but it would hold either a symbol string or a list (JSON) as its compiled expression.

**Comment by seandavi** [comment]
The SolrPromise stuff is VERY impressive. I'll spend some time on that one, as it seems like the Pro version of what I wanted to do. I can see this approach being useful in all kinds of API work.

**Comment by mtmorgan** [comment]
Is there an (promise :) of an) updated patch to replace the current version? Not wanting to loose sight of the trees for the forest...

**Comment by seandavi** [comment]
I am traveling for the next 2.5 weeks, so promise is perhaps a bit strong in both senses of the word.  If anyone wants to either move forward with my juvenile approach or wants to go with the adult version instead, I won’t take it personally.  That said, I do plan to work on this some when I can.

**Comment by seandavi** [comment]
Closing this one and replacing with new pull request.

**Pull request closed without merging**
